# 接下来的两条命令是为了解决 Docker 使用中一些奇形怪状的问题
- name: uninstall urllib3 chardet
  become: yes
  pip: 
    executable: pip2
    name: 
      - urllib3
      - chardet
    state: absent
- name: install requests
  become: yes
  pip: 
    executable: pip2
    name: 
      - requests
      - jsondiff
    state: latest 
# 接下来的两条命令是为了解决 Docker 使用中一些奇形怪状的问题
- name: uninstall urllib3 chardet
  become: yes
  pip: 
    executable: pip3
    name: 
      - urllib3
      - chardet
    state: absent
- name: install requests
  become: yes
  pip: 
    executable: pip3
    name: 
      - requests
      - jsondiff
    state: latest