# Get Docker CE for Ubuntu https://docs.docker.com/install/linux/docker-ce/ubuntu/
- name: Uninstall old versions
  become: yes
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
- name: Install packages to allow apt to use a repository over HTTPS
  become: true
  apt:
    update_cache: yes 
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: latest
- name: Add Docker’s official GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
- name: Use the following command to set up the stable repository
  become: yes
  apt_repository: 
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
- name: Install the latest version of Docker CE and containerd
  become: true
  apt:
    update_cache: yes 
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest