- name: set timezone
  become: yes
  timezone:
    name: "{{ TZ }}"
- name: update yum
  become: true
  yum:
    name: 
      - curl
      - wget
      - vim
      - git
      - mosh
      - screen
    update_cache: yes
    state: latest
- name: copy .inputrc
  become: yes
  copy:
    src: roles/common/files/dotfile/.inputrc
    dest: /root/.inputrc
- name: copy .vimrc
  become: yes
  copy:
    src: roles/common/files/dotfile/.vimrc
    dest: /root/.vimrc